#!/usr/bin/env python3
# encoding: utf-8

import configparser
import json
import os
import subprocess
import sys

host = "localhost:9526"
clientPath = "/usr/share/openqa/script/client"
isotovieoPath = "/usr/lib/os-autoinst/isotovideo"
defaultParamsConfPath = "/etc/openqa/deepin.ini"


def resultToJsonStr(result):
    if len(result) < 2:  # at least "{}"
        return
    result = result.decode("utf-8")
    jsonStr = result.replace(r'\"', '"')[1:-2]
    return jsonStr



def initParams(params):

    params = params.strip()
    keys = [p.split("=")[0].strip() for p in params.split(" ") if "=" in p]

    if "DISTRI" in keys:
        print("You don't need set the DIRSTRI in params, please remove it and try again.")
        quit(-1)

    if len(params.strip()) == 0:
        params += "DISTRI=deepin"
    else:
        params += ",DISTRI=deepin"

    if "ISO" not in keys:
        iso = getDefaultParam("ISO")
        if iso:
            params += ",ISO=%s" % iso
        else:
            build = getDefaultParam("BUILD")
            if build:
                params += ",ISO=deepin-sid-amd64%s%s.iso" % ("_",  build)
            else:
                params += ",ISO=deepin-sid-amd64.iso"

    if "FLAVOR" not in keys:
        flavor = getDefaultParam("FLAVOR")
        if flavor:
            params += ",FLAVOR=%s" % flavor
        else:
            params += ",FLAVOR=SID-DVD"

    if "ARCH" not in keys:
        arch = getDefaultParam("ARCH")
        if arch:
            params += ",ARCH=%s" % arch
        else:
            params += ",ARCH=x86_64"

    if "VERSION" not in keys:
        version = getDefaultParam("VERSION")
        if version:
            params += ",VERSION=%s" % version
        else:
            params += ",VERSION=2015"

    if "USERNAME" not in keys:
        username = getDefaultParam("USERNAME")
        if username:
            params += ",USERNAME=%s" % username
        else:
            params += ",USERNAME=deepin"

    if "USERPWD" not in keys:
        userpwd = getDefaultParam("USERPWD")
        if userpwd:
            params += ",USERPWD=%s" % userpwd
        else:
            params += ",USERPWD=deepin"

    if "HDDSIZEGB" not in keys:
        size = getDefaultParam("HDDSIZEGB")
        if size:
            params += ",HDDSIZEGB=%s" % size
        else:
            params += ",HDDSIZEGB=10"

    paramDict = getExtensionParams()
    for (k, v) in paramDict.items():
        k = k.upper()
        if k not in params:
            params += ",%s=%s" %(k, v)

    return params


defaultParamsConfig = None
def getDefaultParam(key):

    global defaultParamsConfig
    if not defaultParamsConfig:
        if not os.path.exists(defaultParamsConfPath):
            return ""
        defaultParamsConfig = configparser.ConfigParser()
        defaultParamsConfig.read(defaultParamsConfPath)

    if key in defaultParamsConfig["DEFAULT"]:
        return defaultParamsConfig["DEFAULT"][key]

    return ""

def getExtensionParams():

    params = {}

    if not os.path.exists(defaultParamsConfPath):
        return params
    config = configparser.ConfigParser()
    config.read(defaultParamsConfPath)

    section = "EXTENSION"
    items = config.items(section)
    for (k, v) in items:
        params[k] = v

    return params

def scheduledJobs(params):
    cmds = []
    cmds.append(clientPath)
    cmds.append("--host")
    cmds.append(host)
    #cmds.append("--rawjson")
    cmds.append("isos")
    cmds.append("post")
    cmds += [ p.strip() for p in params.split(",") if len(p.strip()) > 0]

    print (" ".join(cmds))

    # execute
    try:
        result = subprocess.check_output(cmds, env={"OPENQA_CONFIG":"/etc/openqa"})
    except subprocess.CalledProcessError as e:
        print (e)
        result = e.output.decode("utf-8")
        print ("output: ", result)
        quit(-1)

    # tmp
    result = result.decode("utf-8")
    print ("output: ", result)
    return 0

    jsonStr = resultToJsonStr(result)

    if (jsonStr == None):
        print("Get a null result from server when scheduled jobs, abort.")
        quit(-1)

    jsonData = json.loads(jsonStr)
    jobIds = jsonData.get("ids")

    if len(jobIds) == 0:
        print("No job has been created, please check your params for Startup")
        quit(-1)

    print("scheduled Result:", jsonStr)

    return jobIds

def startWorker():
    cmds = []
    cmds.append("/usr/share/openqa/script/worker")
    cmds.append("--instance")
    cmds.append("1")
    cmds.append("--isotovideo")
    cmds.append(isotovieoPath)
    #cmds.append("--no-cleanup")
    try:
        subprocess.check_call(cmds, stdout=sys.stdout)
    except subprocess.CalledProcessError as e:
        print (e)
        print ("output: ", e.output.decode("utf-8"))
        #raise e

if __name__ == "__main__":

    rawParams = ""
    if len(sys.argv) == 2:
        rawParams = sys.argv[1]

    if len(sys.argv) > 2:
        rawParams = ",".join(sys.argv[1:])

    params = initParams(rawParams)

    scheduledJobs(params)

